name: flame-fitting
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - eigen
  - pip:
    - chumpy
    - opencv-python
    - Cython
    - werkzeug
    - # additional for internal mesh build
    - numpy
    - setuptools
    - matplotlib
    - scipy
    - pyopengl
    - pillow
    - pyzmq
    - pyyaml
